Description: ECS Services

Parameters:
  ECSCluster:
    Type: String

  ECSServiceRole:
    Type: String

  TargetGroup:
    Type: String

  ECSTaskRole:
    Type: String

  DockerRepository:
    Type: String

  ProjectName:
    Description: projectName
    Type: String
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: bridge
      Family: !Sub ${ProjectName}-TaskFamily
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${ECSTaskRole}
      ContainerDefinitions:
        - Name: !Sub ${ProjectName}Container
          Image: !Sub ${DockerRepository}:latest
          Essential: true
          MemoryReservation: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 80
              HostPort: 0
              Protocol: tcp
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      ServiceName: !Sub ${ProjectName}-Service
      Role: !Ref ECSServiceRole
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      LoadBalancers:
        - ContainerName: !Sub ${ProjectName}Container
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
Outputs:
  FamilyName:
    Value: !Sub ${ProjectName}-TaskFamily
