Description: ECS Clusters

Parameters:
  ClusterName:
    Type: String

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

Outputs:
  ECSCluster:
      Value: !Ref Cluster
