AWSTemplateFormatVersion: '2010-09-09'

Description: IAM Roles

Parameters:
  ProjectName:
    Description: projectName
    Type: String
  
Resources:
  TaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${ProjectName}-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"

Outputs:
  TaskRole:
    Value: !Ref TaskRole