AWSTemplateFormatVersion: '2010-09-09'

Description: Creation of load balancer security group

Parameters:
  ProjectName:
    Type: String

Resources:
  AlbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ProjectName}-load-balancer-sg
      GroupDescription: !Sub ${ProjectName}-load-balancer-sg
      SecurityGroupIngress:
      -
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      -
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIpv6: ::/0
      -
        IpProtocol: tcp
        FromPort: 443
        ToPort: 44380
        CidrIp: 0.0.0.0/0
      -
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIpv6: ::/0
      Tags:
      - Key: Name
        Value: !Sub ${ProjectName}-load-balancer-sg

Outputs:
  AlbSg:
    Value: !GetAtt AlbSg.GroupId