AWSTemplateFormatVersion: '2010-09-09'

Description: Application Load Balancer

Parameters:
  ProjectName:
    Type: String

  Subnets:
    Description: Choose which subnets the Applicaion Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select the Security Group to apply to the Application Load Balancer
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-load-balancer
      Subnets: !Ref Subnets
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: false
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-load-balancer
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  ServiceUrl:
    Value: !Sub http://${LoadBalancer.DNSName}
  ServiceId:
    Value: !GetAtt LoadBalancer.DNSName
  AlbName:
    Value: !GetAtt LoadBalancer.LoadBalancerFullName
